# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d90491a9f3432c65782b21042aa8cde86a11e2ebb6ca31899bcd814de52b733f9eb21b50aa6815adc9b77408536ddf04c84031d64049d47889d6432f92b49d4c

test:
  secret_key_base: ac1e7437f8fb4cae951702c7cd42f2e98b2d486ec79591cd5b5a5b2506ceb86930e7521ab49ace503d048984c9f40e809092f8fdeb3b512a390c84a38e96a2b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
